from playwright.sync_api import sync_playwright
errs=[]
with sync_playwright() as p:
    b=p.chromium.launch();pg=b.new_page(viewport={'width':1300,'height':900})
    pg.on('pageerror',lambda e:errs.append('PAGEERR '+str(e)))
    pg.on('console',lambda m:errs.append('CONSOLE '+m.text) if m.type=='error' else None)
    pg.on('dialog',lambda d:d.accept('My arc' if d.type=='prompt' else None))
    pg.goto('http://localhost:3111');pg.wait_for_timeout(800)
    pg.evaluate("sw('sf-river')");pg.wait_for_timeout(300)
    pg.evaluate("S.ar={a:['anya'],b:['arjun'],init:1};S.tab='arcs';render()")
    pg.click('[data-cli^="ar:"] button[data-v5=seed]')
    pg.click('[data-cli^="ar:"] button[data-v5=tpl]');pg.wait_for_timeout(150)
    print('templates',pg.evaluate("document.querySelectorAll('#tpl5 [data-v5=tuse]').length"))
    pg.click('#tpl5 button[data-v5=tgf][data-g="Romance"]')
    pg.screenshot(path='tpl.png')
    pg.click('#tpl5 button[data-v5=tuse] >> nth=0');pg.wait_for_timeout(200)
    print('applied',pg.evaluate("S.rels.find(r=>r.a=='anya'&&r.b=='arjun').tg.map(x=>x.l).join(',')"),pg.evaluate("S.rels.find(r=>r.a=='anya'&&r.b=='arjun').tgn.n"))
    print('chart label',pg.evaluate("document.querySelector('#arcviz svg').textContent.includes('Dark moment')"))
    pg.click('[data-cli^="ar:"] button[data-v5=tsave]');pg.wait_for_timeout(150)
    print('custom saved',pg.evaluate("JSON.parse(localStorage.getItem('sf-ui')).ct.length"))
    pg.click('[data-cli^="ar:"] button[data-v5=tpl]');pg.click('#tpl5 button[data-v5=tgf][data-g="My templates"]')
    print('mine listed',pg.evaluate("document.querySelectorAll('#tpl5 [data-v5=tdelc]').length"))
    pg.click('#dr [data-a=cd]')
    pg.evaluate("window.scrollTo(0,0)");pg.screenshot(path='theme.png')
    pg.evaluate("document.documentElement.dataset.theme='dark'");pg.screenshot(path='dark.png')
    b.close()
print('ERRORS',errs)
