from playwright.sync_api import sync_playwright
errs=[]
with sync_playwright() as p:
    b=p.chromium.launch();pg=b.new_page(viewport={'width':1300,'height':850})
    pg.on('pageerror',lambda e:errs.append('PAGEERR '+str(e)))
    pg.on('console',lambda m:errs.append('CONSOLE '+m.text) if m.type=='error' else None)
    pg.on('dialog',lambda d:d.accept('v1 draft') if d.type=='prompt' else d.accept())
    pg.goto('http://localhost:3111');pg.wait_for_timeout(800)
    pg.evaluate("sw('sf-river')");pg.wait_for_timeout(300)
    pg.evaluate("S.tab='book';S.bk={fmt:'book',ord:'time',edit:1};render()")
    print('toolbar btns',pg.evaluate("[...document.querySelectorAll('#app [data-v5=fcs],#app [data-v5=hist]')].length"))
    # manual snapshot via editor history
    pg.click('button[data-v5=hist]');pg.wait_for_timeout(150)
    pg.fill('#snn','baseline');pg.click('button[data-v5=snew]')
    print('snaps',pg.evaluate("rdS?0:0") if False else pg.evaluate("JSON.parse(localStorage.getItem('sf-snaps-'+KEY)).length"))
    pg.click('#dr [data-a=cd]')
    # focus mode
    pg.click('#app button[data-v5=fcs][data-e=""]')
    print('focus open',pg.evaluate("!!document.getElementById('foc')"))
    ta=pg.locator('#focta');t0=ta.input_value()
    ta.press('Control+End');ta.type(' Brand new sentence typed in focus mode.')
    print('count',pg.inner_text('#fcnt'))
    print('saved to fin',pg.evaluate("S.ev.some(e=>e.fin&&e.fin.book&&e.fin.book.includes('Brand new sentence'))"))
    pg.screenshot(path='focus.png')
    pg.keyboard.press('Alt+ArrowRight');pg.wait_for_timeout(100)
    print('chapter after nav',pg.inner_text('#foc .fbar small'))
    pg.click('button[data-v5=fctxb]');print('ctx visible',pg.evaluate("getComputedStyle(document.querySelector('#foc .fctx')).display"))
    pg.keyboard.press('Control+s');pg.wait_for_timeout(100)
    print('snaps after ctrl+s',pg.evaluate("JSON.parse(localStorage.getItem('sf-snaps-'+KEY)).length"))
    # history from focus: compare and restore chapter
    pg.click('button[data-v5=fhist]');pg.wait_for_timeout(100)
    pg.click('#dr button[data-v5=scmp]:near(:text("baseline"))') if False else None
    sid=pg.evaluate("JSON.parse(localStorage.getItem('sf-snaps-'+KEY)).find(x=>x.n=='baseline').id")
    pg.click(f'#dr button[data-v5=scmp][data-s="{sid}"]');pg.wait_for_timeout(100)
    print('cmp text',pg.inner_text('#dr')[:160].replace('\n',' | '))
    pg.click('#dr button[data-v5=sdiff]');pg.wait_for_timeout(100)
    print('diff has +',pg.evaluate("!!document.querySelector('#dr .df.da')"))
    pg.screenshot(path='hist.png')
    pg.click('#dr button[data-v5=srestc]');pg.wait_for_timeout(200)
    print('restored (no brand new)',pg.evaluate("!S.ev.some(e=>e.fin&&JSON.stringify(e.fin).includes('Brand new sentence'))"))
    print('auto snap before restore',pg.evaluate("JSON.parse(localStorage.getItem('sf-snaps-'+KEY)).some(x=>x.n.startsWith('Before restoring'))"))
    pg.click('#dr [data-a=cd]')
    pg.keyboard.press('Escape');pg.wait_for_timeout(150)
    print('focus closed',pg.evaluate("!document.getElementById('foc')"))
    # restore all & replace-all auto snapshot
    pg.fill('input[data-v5=fr][data-f=f]','Anya');pg.fill('input[data-v5=fr][data-f=r]','Zed');pg.click('button[data-v5=frall]')
    print('pre-replace snap',pg.evaluate("JSON.parse(localStorage.getItem('sf-snaps-'+KEY)).some(x=>x.n.startsWith('Before replace'))"))
    pg.click('button[data-v5=hist]');pg.click(f'#dr button[data-v5=srest][data-s="{sid}"]');pg.wait_for_timeout(200)
    print('Anya back',pg.evaluate("!S.ev.some(e=>e.fin&&JSON.stringify(e.fin).includes('Zed'))"))
    pg.reload();pg.wait_for_timeout(800)
    print('snaps persist',pg.evaluate("JSON.parse(localStorage.getItem('sf-snaps-'+KEY)).length"))
    b.close()
print('ERRORS',errs)
